/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operando {
	int x;
	int y;
};

typedef struct operando operando;

#define CALCULADORA 300000001
#define CALCULADORA_VERSAO 1

#if defined(__STDC__) || defined(__cplusplus)
#define SOMAR 1
extern  int * somar_1(operando *, CLIENT *);
extern  int * somar_1_svc(operando *, struct svc_req *);

#define SUBTRAIR 2
extern  int * subtrair_1(operando *, CLIENT *);
extern  int * subtrair_1_svc(operando *, struct svc_req *);

#define MULTIPLICAR 3
extern  int * multiplicar_1(operando *, CLIENT *);
extern  int * multiplicar_1_svc(operando *, struct svc_req *);

#define DIVIDIR 4
extern  int * dividir_1(operando *, CLIENT *);
extern  int * dividir_1_svc(operando *, struct svc_req *);

extern int calculadora_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SOMAR 1
extern  int * somar_1();
extern  int * somar_1_svc();

#define SUBTRAIR 2
extern  int * subtrair_1();
extern  int * subtrair_1_svc();

#define MULTIPLICAR 3
extern  int * multiplicar_1();
extern  int * multiplicar_1_svc();

#define DIVIDIR 4
extern  float * dividir_1();
extern  float * dividir_1_svc();

extern int calculadora_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operando (XDR *, operando*);

#else /* K&R C */
extern bool_t xdr_operando ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
